#!/bin/sh -e
case $1 in
  prereqs)
    exit 0
    ;;
esac
mkdir /ro
mkdir /rw
mount -n -o mode=0755 -t tmpfs root-rw /rw
mount -n -o move ${rootmnt} /ro
mount -n -o dirs=/rw:/ro=ro -t aufs root-aufs ${rootmnt}
mkdir ${rootmnt}/ro
mkdir ${rootmnt}/rw
mount -n -o move /ro ${rootmnt}/ro
mount -n -o move /rw ${rootmnt}/rw